export const contactPresets = {
  // === БАЗОВЫЕ СТИЛИ ===
  CORPORATE: {
    name: 'Корпоративный',
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
    gradientColor1: '#ffffff',
    gradientColor2: '#f5f5f5',
    gradientDirection: 'to bottom',
    titleColor: '#1a237e',
    descriptionColor: '#455a64',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#e0e0e0',
    infoBorderColor: '#e0e0e0',
    labelColor: '#455a64',
    inputBackgroundColor: '#f5f5f5',
    inputTextColor: '#000000',
    buttonColor: '#1a237e',
    buttonTextColor: '#ffffff',
    iconColor: '#1a237e',
    infoTitleColor: '#1a237e',
    infoTextColor: '#455a64'
  },
  MODERN: {
    name: 'Современный',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#fafafa',
    gradientColor1: '#fafafa',
    gradientColor2: '#e0e0e0',
    gradientDirection: 'to bottom',
    titleColor: '#6200ea',
    descriptionColor: '#424242',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#7c4dff',
    infoBorderColor: '#e0e0e0',
    labelColor: '#424242',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#6200ea',
    buttonTextColor: '#ffffff',
    iconColor: '#6200ea',
    infoTitleColor: '#6200ea',
    infoTextColor: '#424242'
  },
  MINIMAL: {
    name: 'Минималистичный',
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
    gradientColor1: '#ffffff',
    gradientColor2: '#f5f5f5',
    gradientDirection: 'to bottom',
    titleColor: '#212121',
    descriptionColor: '#757575',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#eeeeee',
    infoBorderColor: '#e0e0e0',
    labelColor: '#757575',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#212121',
    buttonTextColor: '#ffffff',
    iconColor: '#212121',
    infoTitleColor: '#212121',
    infoTextColor: '#757575'
  },
  NATURE: {
    name: 'Природный',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#f1f8e9',
    gradientColor1: '#f1f8e9',
    gradientColor2: '#c8e6c9',
    gradientDirection: 'to bottom',
    titleColor: '#1b5e20',
    descriptionColor: '#2e7d32',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#a5d6a7',
    infoBorderColor: '#e0e0e0',
    labelColor: '#2e7d32',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#1b5e20',
    buttonTextColor: '#ffffff',
    iconColor: '#1b5e20',
    infoTitleColor: '#1b5e20',
    infoTextColor: '#2e7d32'
  },
  OCEAN: {
    name: 'Океан',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#e1f5fe',
    gradientColor1: '#e1f5fe',
    gradientColor2: '#b3e5fc',
    gradientDirection: 'to bottom',
    titleColor: '#01579b',
    descriptionColor: '#0277bd',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#81d4fa',
    infoBorderColor: '#e0e0e0',
    labelColor: '#0277bd',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#01579b',
    buttonTextColor: '#ffffff',
    iconColor: '#01579b',
    infoTitleColor: '#01579b',
    infoTextColor: '#0277bd'
  },
  SUNSET: {
    name: 'Закат',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#fff3e0',
    gradientColor1: '#fff3e0',
    gradientColor2: '#ffe0b2',
    gradientDirection: 'to bottom',
    titleColor: '#bf360c',
    descriptionColor: '#d84315',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#ffab91',
    infoBorderColor: '#e0e0e0',
    labelColor: '#f4511e',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#e64a19',
    buttonTextColor: '#ffffff',
    iconColor: '#e64a19',
    infoTitleColor: '#e64a19',
    infoTextColor: '#f4511e'
  },
  DARK_MODE: {
    name: 'Тёмный режим',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#263238',
    gradientColor1: '#263238',
    gradientColor2: '#37474f',
    gradientDirection: 'to bottom',
    titleColor: '#ffffff',
    descriptionColor: '#b0bec5',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#37474f',
    infoBackgroundColor: '#37474f',
    formBorderColor: '#455a64',
    infoBorderColor: '#455a64',
    labelColor: '#b0bec5',
    inputBackgroundColor: '#37474f',
    inputTextColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#263238',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#b0bec5'
  },
  PASTEL: {
    name: 'Пастельный',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#f3e5f5',
    gradientColor1: '#f3e5f5',
    gradientColor2: '#e1bee7',
    gradientDirection: 'to bottom',
    titleColor: '#6a1b9a',
    descriptionColor: '#8e24aa',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#ce93d8',
    infoBorderColor: '#e0e0e0',
    labelColor: '#8e24aa',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#6a1b9a',
    buttonTextColor: '#ffffff',
    iconColor: '#6a1b9a',
    infoTitleColor: '#6a1b9a',
    infoTextColor: '#8e24aa'
  },
  FOREST: {
    name: 'Лесной',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#e8f5e9',
    gradientColor1: '#e8f5e9',
    gradientColor2: '#c8e6c9',
    gradientDirection: 'to bottom',
    titleColor: '#1b5e20',
    descriptionColor: '#2e7d32',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#a5d6a7',
    infoBorderColor: '#e0e0e0',
    labelColor: '#2e7d32',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#1b5e20',
    buttonTextColor: '#ffffff',
    iconColor: '#1b5e20',
    infoTitleColor: '#1b5e20',
    infoTextColor: '#2e7d32'
  },
  ROYAL: {
    name: 'Королевский',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#f3e5f5',
    gradientColor1: '#f3e5f5',
    gradientColor2: '#e1bee7',
    gradientDirection: 'to bottom',
    titleColor: '#ff0000',
    descriptionColor: '#ff0000',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#ce93d8',
    infoBorderColor: '#e0e0e0',
    labelColor: '#8e24aa',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#6a1b9a',
    buttonTextColor: '#ffffff',
    iconColor: '#6a1b9a',
    infoTitleColor: '#6a1b9a',
    infoTextColor: '#8e24aa'
  },

  // === НЕОНОВЫЕ СТИЛИ ===
  NEON_BLUE: {
    name: 'Неоновый синий',
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#000033',
    gradientColor1: '#000033',
    gradientColor2: '#000066',
    gradientDirection: '45deg',
    titleColor: '#00ffff',
    descriptionColor: '#00b8d4',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#000066',
    infoBackgroundColor: '#000066',
    formBorderColor: '#00ffff',
    infoBorderColor: '#00ffff',
    labelColor: '#00b8d4',
    inputBackgroundColor: '#000066',
    inputTextColor: '#ffffff',
    buttonColor: '#00ffff',
    buttonTextColor: '#000033',
    iconColor: '#00ffff',
    infoTitleColor: '#00ffff',
    infoTextColor: '#00b8d4'
  },
  NEON_PURPLE: {
    name: 'Неоновый фиолетовый',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#1a0033',
    gradientColor1: '#1a0033',
    gradientColor2: '#330066',
    gradientDirection: '45deg',
    // Основные цвета
    titleColor: '#ff00ff',
    descriptionColor: '#ea80fc',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#330066',
    infoBackgroundColor: '#330066',
    formBorderColor: '#ff00ff',
    infoBorderColor: '#ff00ff',
    labelColor: '#ea80fc',
    inputBackgroundColor: '#330066',
    inputTextColor: '#ffffff',
    buttonColor: '#ff00ff',
    buttonTextColor: '#1a0033',
    iconColor: '#ff00ff',
    infoTitleColor: '#ff00ff',
    infoTextColor: '#ea80fc'
  },
  NEON_GREEN: {
    name: 'Неоновый зелёный',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#001a00',
    gradientColor1: '#001a00',
    gradientColor2: '#142e14',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#00ff00',
    descriptionColor: '#69f0ae',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#003300',
    infoBackgroundColor: '#003300',
    formBorderColor: '#00ff00',
    infoBorderColor: '#00ff00',
    labelColor: '#69f0ae',
    inputBackgroundColor: '#003300',
    inputTextColor: '#ffffff',
    buttonColor: '#00ff00',
    buttonTextColor: '#001a00',
    iconColor: '#00ff00',
    infoTitleColor: '#00ff00',
    infoTextColor: '#69f0ae'
  },
  NEON_RAINBOW: {
    name: 'Неоновая радуга',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#000033',
    gradientColor1: '#000033',
    gradientColor2: '#141447',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ff0080',
    descriptionColor: '#80ff00',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#1a1a1a',
    infoBackgroundColor: '#1a1a1a',
    formBorderColor: '#ff0080',
    infoBorderColor: '#ff0080',
    labelColor: '#80ff00',
    inputBackgroundColor: '#1a1a1a',
    inputTextColor: '#ffffff',
    buttonColor: '#ff0080',
    buttonTextColor: '#000033',
    iconColor: '#ff0080',
    infoTitleColor: '#ff0080',
    infoTextColor: '#80ff00'
  },
  NEON_CYBERPUNK: {
    name: 'Неон-Киберпанк',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#0a0a1f',
    gradientColor1: '#0a0a1f',
    gradientColor2: '#1e1e33',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#00fff5',
    descriptionColor: '#ffffff',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#000033',
    infoBackgroundColor: '#000033',
    formBorderColor: '#00fff5',
    infoBorderColor: '#00fff5',
    labelColor: '#ffffff',
    inputBackgroundColor: '#000033',
    inputTextColor: '#ffffff',
    buttonColor: '#00fff5',
    buttonTextColor: '#0a0a1f',
    iconColor: '#00fff5',
    infoTitleColor: '#00fff5',
    infoTextColor: '#ffffff'
  },
  NEON_SUNSET: {
    name: 'Неоновый закат',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#1a0033',
    gradientColor1: '#1a0033',
    gradientColor2: '#2e1447',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ff0066',
    descriptionColor: '#ff6600',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#330066',
    infoBackgroundColor: '#330066',
    formBorderColor: '#ff0066',
    infoBorderColor: '#ff0066',
    labelColor: '#ff6600',
    inputBackgroundColor: '#330066',
    inputTextColor: '#ffffff',
    buttonColor: '#ff0066',
    buttonTextColor: '#1a0033',
    iconColor: '#ff0066',
    infoTitleColor: '#ff0066',
    infoTextColor: '#ff6600'
  },
  NEON_CYAN: {
    name: 'Неоновый циан',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#006064',
    gradientColor1: '#006064',
    gradientColor2: '#147478',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#e0f7fa',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#00838f',
    infoBackgroundColor: '#00838f',
    formBorderColor: '#00acc1',
    infoBorderColor: '#00acc1',
    labelColor: '#e0f7fa',
    inputBackgroundColor: '#00838f',
    inputTextColor: '#ffffff',
    buttonColor: '#18ffff',
    buttonTextColor: '#006064',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#e0f7fa'
  },
  NEON_MAGENTA: {
    name: 'Неоновая пурпурная',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#1a001a',
    gradientColor1: '#1a001a',
    gradientColor2: '#2e142e',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#ff69b4',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#330033',
    infoBackgroundColor: '#330033',
    formBorderColor: '#ff1493',
    infoBorderColor: '#ff1493',
    labelColor: '#ff69b4',
    inputBackgroundColor: '#330033',
    inputTextColor: '#ffffff',
    buttonColor: '#ff1493',
    buttonTextColor: '#1a001a',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#ff69b4'
  },
  NEON_ELECTRIC: {
    name: 'Неоновый электрик',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#001a1a',
    gradientColor1: '#001a1a',
    gradientColor2: '#142e2e',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#00ffff',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#003333',
    infoBackgroundColor: '#003333',
    formBorderColor: '#00cccc',
    infoBorderColor: '#00cccc',
    labelColor: '#00ffff',
    inputBackgroundColor: '#003333',
    inputTextColor: '#ffffff',
    buttonColor: '#00ffff',
    buttonTextColor: '#001a1a',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#00ffff'
  },
  NEON_ACID: {
    name: 'Неоновый кислотный',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#0d1a00',
    gradientColor1: '#0d1a00',
    gradientColor2: '#1a2b00',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#00ff00',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#1a3300',
    infoBackgroundColor: '#1a3300',
    formBorderColor: '#66ff00',
    infoBorderColor: '#66ff00',
    labelColor: '#00ff00',
    inputBackgroundColor: '#1a3300',
    inputTextColor: '#ffffff',
    buttonColor: '#66ff00',
    buttonTextColor: '#0d1a00',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#00ff00'
  },
  NEON_PLASMA: {
    name: 'Неоновая плазма',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#1a0011',
    gradientColor1: '#1a0011',
    gradientColor2: '#2e1425',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#ff00aa',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#330022',
    infoBackgroundColor: '#330022',
    formBorderColor: '#ff0066',
    infoBorderColor: '#ff0066',
    labelColor: '#ff00aa',
    inputBackgroundColor: '#330022',
    inputTextColor: '#ffffff',
    buttonColor: '#ff0066',
    buttonTextColor: '#1a0011',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#ff00aa'
  },
  NEON_VOLTAGE: {
    name: 'Неоновое напряжение',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#1a1a00',
    gradientColor1: '#1a1a00',
    gradientColor2: '#2b2b00',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#ffff00',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#333300',
    infoBackgroundColor: '#333300',
    formBorderColor: '#ffff00',
    infoBorderColor: '#ffff00',
    labelColor: '#ffff00',
    inputBackgroundColor: '#333300',
    inputTextColor: '#ffffff',
    buttonColor: '#ffff00',
    buttonTextColor: '#1a1a00',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#ffff00'
  },

  // === ПРИРОДНЫЕ/ЭЛЕМЕНТЫ ===
  OCEAN_WAVE: {
    name: 'Океанская волна',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#e0f7fa',
    gradientColor1: '#e0f7fa',
    gradientColor2: '#f4ffff',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#01579b',
    descriptionColor: '#0277bd',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#4dd0e1',
    infoBorderColor: '#4dd0e1',
    labelColor: '#0277bd',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#01579b',
    buttonTextColor: '#ffffff',
    iconColor: '#01579b',
    infoTitleColor: '#01579b',
    infoTextColor: '#0277bd'
  },
  MAGENTA_GLOW: {
    name: 'Пурпурное свечение',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#fce4ec',
    gradientColor1: '#fce4ec',
    gradientColor2: '#fff8ff',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ad1457',
    descriptionColor: '#c2185b',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#f06292',
    infoBorderColor: '#f06292',
    labelColor: '#c2185b',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#ad1457',
    buttonTextColor: '#ffffff',
    iconColor: '#ad1457',
    infoTitleColor: '#ad1457',
    infoTextColor: '#c2185b'
  },
  FIRE_BURST: {
    name: 'Вспышка огня',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#d84315',
    gradientColor1: '#d84315',
    gradientColor2: '#ec5729',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#ffab91',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#bf360c',
    infoBackgroundColor: '#bf360c',
    formBorderColor: '#ff5722',
    infoBorderColor: '#ff5722',
    labelColor: '#ffab91',
    inputBackgroundColor: '#bf360c',
    inputTextColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#d84315',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#ffab91'
  },
  VIOLET_STORM: {
    name: 'Фиолетовая буря',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#4527a0',
    gradientColor1: '#4527a0',
    gradientColor2: '#593bb4',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#d1c4e9',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#311b92',
    infoBackgroundColor: '#311b92',
    formBorderColor: '#512da8',
    infoBorderColor: '#512da8',
    labelColor: '#d1c4e9',
    inputBackgroundColor: '#311b92',
    inputTextColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#4527a0',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#d1c4e9'
  },
  ELECTRIC_LIME: {
    name: 'Электрический лайм',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#f1f8e9',
    gradientColor1: '#f1f8e9',
    gradientColor2: '#fffffd',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#33691e',
    descriptionColor: '#689f38',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#8bc34a',
    infoBorderColor: '#8bc34a',
    labelColor: '#689f38',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#33691e',
    buttonTextColor: '#ffffff',
    iconColor: '#33691e',
    infoTitleColor: '#33691e',
    infoTextColor: '#689f38'
  },
  DEEP_OCEAN: {
    name: 'Глубокий океан',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#006064',
    gradientColor1: '#006064',
    gradientColor2: '#147478',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#80deea',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#00838f',
    infoBackgroundColor: '#00838f',
    formBorderColor: '#00acc1',
    infoBorderColor: '#00acc1',
    labelColor: '#80deea',
    inputBackgroundColor: '#00838f',
    inputTextColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#006064',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#80deea'
  },
  ROSE_GOLD: {
    name: 'Розовое золото',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#fce4ec',
    gradientColor1: '#fce4ec',
    gradientColor2: '#fff8ff',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ad1457',
    descriptionColor: '#c2185b',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#f06292',
    infoBorderColor: '#f06292',
    labelColor: '#c2185b',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#ad1457',
    buttonTextColor: '#ffffff',
    iconColor: '#ad1457',
    infoTitleColor: '#ad1457',
    infoTextColor: '#c2185b'
  },
  SILVER_MIST: {
    name: 'Серебряный туман',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#eceff1',
    gradientColor1: '#eceff1',
    gradientColor2: '#ffffff',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#263238',
    descriptionColor: '#37474f',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#607d8b',
    infoBorderColor: '#607d8b',
    labelColor: '#37474f',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#263238',
    buttonTextColor: '#ffffff',
    iconColor: '#263238',
    infoTitleColor: '#263238',
    infoTextColor: '#37474f'
  },
  TROPICAL_PARADISE: {
    name: 'Тропический рай',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#e0f2f1',
    gradientColor1: '#e0f2f1',
    gradientColor2: '#f4ffff',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#004d40',
    descriptionColor: '#00695c',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#00897b',
    infoBorderColor: '#00897b',
    labelColor: '#00695c',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#004d40',
    buttonTextColor: '#ffffff',
    iconColor: '#004d40',
    infoTitleColor: '#004d40',
    infoTextColor: '#00695c'
  },
  GOLDEN_HOUR: {
    name: 'Золотой час',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#fff8e1',
    gradientColor1: '#fff8e1',
    gradientColor2: '#fffff5',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#e65100',
    descriptionColor: '#f57c00',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#ffc107',
    infoBorderColor: '#ffc107',
    labelColor: '#f57c00',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#e65100',
    buttonTextColor: '#ffffff',
    iconColor: '#e65100',
    infoTitleColor: '#e65100',
    infoTextColor: '#f57c00'
  },

  // === КОСМИЧЕСКИЕ/ТЕМНЫЕ ===
  COSMIC_BLUE: {
    name: 'Космический синий',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#0d47a1',
    gradientColor1: '#0d47a1',
    gradientColor2: '#215bb5',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#e3f2fd',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#1565c0',
    infoBackgroundColor: '#1565c0',
    formBorderColor: '#1976d2',
    infoBorderColor: '#1976d2',
    labelColor: '#e3f2fd',
    inputBackgroundColor: '#1565c0',
    inputTextColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#0d47a1',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#e3f2fd'
  },
  ROYAL_PURPLE: {
    name: 'Королевский фиолетовый',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#311b92',
    gradientColor1: '#311b92',
    gradientColor2: '#452fa6',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#ede7f6',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#512da8',
    infoBackgroundColor: '#512da8',
    formBorderColor: '#673ab7',
    infoBorderColor: '#673ab7',
    labelColor: '#ede7f6',
    inputBackgroundColor: '#512da8',
    inputTextColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#311b92',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#ede7f6'
  },
  MIDNIGHT_FOREST: {
    name: 'Полуночный лес',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#1b5e20',
    gradientColor1: '#1b5e20',
    gradientColor2: '#2f7234',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#a5d6a7',
    descriptionColor: '#c8e6c9',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#2e7d32',
    infoBackgroundColor: '#2e7d32',
    formBorderColor: '#43a047',
    infoBorderColor: '#43a047',
    labelColor: '#c8e6c9',
    inputBackgroundColor: '#2e7d32',
    inputTextColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#1b5e20',
    iconColor: '#a5d6a7',
    infoTitleColor: '#a5d6a7',
    infoTextColor: '#c8e6c9'
  },
  SPACE_NEBULA: {
    name: 'Космическая туманность',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'gradient',
    backgroundColor: '#1a0033',
    gradientColor1: '#1a0033',
    gradientColor2: '#2e1447',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#e1bee7',
    descriptionColor: '#ce93d8',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#2d0052',
    infoBackgroundColor: '#2d0052',
    formBorderColor: '#4a0e7a',
    infoBorderColor: '#4a0e7a',
    labelColor: '#ce93d8',
    inputBackgroundColor: '#2d0052',
    inputTextColor: '#ffffff',
    buttonColor: '#e1bee7',
    buttonTextColor: '#1a0033',
    iconColor: '#e1bee7',
    infoTitleColor: '#e1bee7',
    infoTextColor: '#ce93d8'
  },
  AURORA_GLOW: {
    name: 'Сияние авроры',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#10002b',
    gradientColor1: '#10002b',
    gradientColor2: '#24143f',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#e0aaff',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#3c096c',
    infoBackgroundColor: '#3c096c',
    formBorderColor: '#5a189a',
    infoBorderColor: '#5a189a',
    labelColor: '#e0aaff',
    inputBackgroundColor: '#3c096c',
    inputTextColor: '#ffffff',
    buttonColor: '#e0aaff',
    buttonTextColor: '#10002b',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#e0aaff'
  },
  GALAXY_DREAM: {
    name: 'Галактическая мечта',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#03071e',
    gradientColor1: '#03071e',
    gradientColor2: '#171b32',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#e0aaff',
    descriptionColor: '#c77dff',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#141624',
    infoBackgroundColor: '#141624',
    formBorderColor: '#480ca8',
    infoBorderColor: '#480ca8',
    labelColor: '#c77dff',
    inputBackgroundColor: '#141624',
    inputTextColor: '#ffffff',
    buttonColor: '#e0aaff',
    buttonTextColor: '#03071e',
    iconColor: '#e0aaff',
    infoTitleColor: '#e0aaff',
    infoTextColor: '#c77dff'
  },
  VOLCANIC_FIRE: {
    name: 'Вулканический огонь',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#370617',
    gradientColor1: '#370617',
    gradientColor2: '#4b1a2b',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#ffba08',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#6a040f',
    infoBackgroundColor: '#6a040f',
    formBorderColor: '#dc2f02',
    infoBorderColor: '#dc2f02',
    labelColor: '#ffba08',
    inputBackgroundColor: '#6a040f',
    inputTextColor: '#ffffff',
    buttonColor: '#ffba08',
    buttonTextColor: '#370617',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#ffba08'
  },

  // === ЯРКИЕ/СВЕЖИЕ ===
  CRIMSON_FLAME: {
    name: 'Багровое пламя',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#b71c1c',
    gradientColor1: '#b71c1c',
    gradientColor2: '#cb3030',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ffffff',
    descriptionColor: '#ffebee',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#c62828',
    infoBackgroundColor: '#c62828',
    formBorderColor: '#d32f2f',
    infoBorderColor: '#d32f2f',
    labelColor: '#ffebee',
    inputBackgroundColor: '#c62828',
    inputTextColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#b71c1c',
    iconColor: '#ffffff',
    infoTitleColor: '#ffffff',
    infoTextColor: '#ffebee'
  },
  DESERT_SUNSET: {
    name: 'Закат в пустыне',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#fff3e0',
    gradientColor1: '#fff3e0',
    gradientColor2: '#fffff4',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#d62d20',
    descriptionColor: '#e85d04',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#f48c06',
    infoBorderColor: '#f48c06',
    labelColor: '#e85d04',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#d62d20',
    buttonTextColor: '#ffffff',
    iconColor: '#d62d20',
    infoTitleColor: '#d62d20',
    infoTextColor: '#e85d04'
  },
  ICE_CRYSTAL: {
    name: 'Ледяной кристалл',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#caf0f8',
    gradientColor1: '#caf0f8',
    gradientColor2: '#deffff',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#003566',
    descriptionColor: '#0077b6',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#00b4d8',
    infoBorderColor: '#00b4d8',
    labelColor: '#0077b6',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#003566',
    buttonTextColor: '#ffffff',
    iconColor: '#003566',
    infoTitleColor: '#003566',
    infoTextColor: '#0077b6'
  },
  MINT_FRESH: {
    name: 'Мятная свежесть',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#f1faee',
    gradientColor1: '#f1faee',
    gradientColor2: '#ffffff',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#264653',
    descriptionColor: '#2a9d8f',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#2a9d8f',
    infoBorderColor: '#2a9d8f',
    labelColor: '#2a9d8f',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#264653',
    buttonTextColor: '#ffffff',
    iconColor: '#264653',
    infoTitleColor: '#264653',
    infoTextColor: '#2a9d8f'
  },
  FRESH_LIME: {
    name: 'Свежий лайм',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#d8f3dc',
    gradientColor1: '#d8f3dc',
    gradientColor2: '#ecfff0',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#2d5016',
    descriptionColor: '#52b788',
    companyInfoColor: '#333333',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#ffffff',
    infoBackgroundColor: '#ffffff',
    formBorderColor: '#74c69d',
    infoBorderColor: '#74c69d',
    labelColor: '#52b788',
    inputBackgroundColor: '#ffffff',
    inputTextColor: '#000000',
    buttonColor: '#2d5016',
    buttonTextColor: '#ffffff',
    iconColor: '#2d5016',
    infoTitleColor: '#2d5016',
    infoTextColor: '#52b788'
  },
  RETRO_WAVE: {
    name: 'Ретро волна',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#03071e',
    gradientColor1: '#03071e',
    gradientColor2: '#171b32',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ff006e',
    descriptionColor: '#fb5607',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#240046',
    infoBackgroundColor: '#240046',
    formBorderColor: '#ff006e',
    infoBorderColor: '#ff006e',
    labelColor: '#ffbe0b',
    inputBackgroundColor: '#240046',
    inputTextColor: '#ffffff',
    buttonColor: '#ff006e',
    buttonTextColor: '#03071e',
    iconColor: '#ff006e',
    infoTitleColor: '#ff006e',
    infoTextColor: '#fb5607'
  },
  CYBER_PUNK: {
    name: 'Киберпанк',
    // Настройки фона секции
    showBackground: true,
    backgroundType: 'solid',
    backgroundColor: '#0d0d0d',
    gradientColor1: '#0d0d0d',
    gradientColor2: '#212121',
    gradientDirection: 'to bottom',
    // Основные цвета
    titleColor: '#ff073a',
    descriptionColor: '#f72585',
    companyInfoColor: '#ffffff',
    formVariant: 'outlined',
    infoVariant: 'elevation',
    formBackgroundColor: '#1a0d1a',
    infoBackgroundColor: '#1a0d1a',
    formBorderColor: '#ff073a',
    infoBorderColor: '#ff073a',
    labelColor: '#f72585',
    inputBackgroundColor: '#1a0d1a',
    inputTextColor: '#ffffff',
    buttonColor: '#ff073a',
    buttonTextColor: '#0d0d0d',
    iconColor: '#ff073a',
    infoTitleColor: '#ff073a',
    infoTextColor: '#f72585'
  }
}; 